### ISSUE TITLE
README is often not rendered on crates.io when using Chrome

### ISSUE THREAD

**Issue by aloucks** [rust-lang/crates.io#2497]
As the title states, the README markdown is often not rendered in Chrome. When using Firefox, this issue doesn't seem to happen or happens infrequently enough that I can't reproduce it. While examining the network tab in developer tools, the connection will show "(pending)" and "stalled" in the details.

Refreshing repeatedly will alternate between the plain description and the rendered readme:

![image](https://user-images.githubusercontent.com/221559/81368994-39bc0c80-90bf-11ea-874f-d7c713cb34ae.png)

![image](https://user-images.githubusercontent.com/221559/81369046-607a4300-90bf-11ea-8853-943c70b2faaf.png)

**Comment by jtgeibel** [comment]
I'm not sure what is going on here yet, but I noticed 1 thing that could be related. When doing some local testing I noticed that when using the `civet` backend our redirect for the readme takes 30 seconds to load for me in Firefox. Debugging with `curl -v` it looks like we send a 302 with a `Location` header, but curl complains that "no chunk, no close, no size. Assume close to signal end". The issue appears to be that `Content-Length: 0` is not sent, and curl is waiting for the connection to be closed.

```text
< HTTP/1.1 302 Found
< location: /readmes/readme-and-deps/readme-and-deps-0.1.3.html
* no chunk, no close, no size. Assume close to signal end
<
```

Interestingly, after 30 seconds the following appears in the console and curl exits:

```text
HTTP/1.1 500 Server Error
Content-Length: 48
Date: Fri, 15 May 2020 00:36:09 GMT
Connection: keep-alive

Error 500: Server Error
* Closing connection 0
Client closed connection
```

It appears that civet is keeping the connection open until a timeout is hit, and is then attempting to send an error response which is interpreted as the response body because the response headers have already been sent.

In production, we run behind nginx and that appears to be masking this issue in most cases. It's possible that some requests still hang in a similar way. For what it's worth, I haven't been able to replicate this issue in production with Chrome, Chromium, or Firefox.

Alternatively, when running `USE_HYPER=1 cargo run --bin server` locally, I see the following:

```text
< HTTP/1.1 302 Found
< location: /readmes/readme-and-deps/readme-and-deps-0.1.3.html
< content-length: 0
< date: Fri, 15 May 2020 00:45:41 GMT
< 
* Connection #0 to host localhost left intact
```

It appears that hyper is automatically adding `Content-Length` and `Date` headers, and then immediately closing the connection.

Hopefully switching to hyper as our web server will resolve this. We can also try explicitly setting `Content-Length: 0` in our redirect response to see if that causes the connection to be closed by civet when expected. (Although we should also look into fixing this upstream in our civet bindings.) It's also possible this has nothing to do with the observed behavior, but it seems like a reasonable lead given the references to "(pending)" and "stalled".

**Comment by jtgeibel** [comment]
@aloucks can you still replicate this behavior? I wasn't able to able to replicate it myself so I can't verify if it is now fixed. We've now switched to `hyper` as our web server, and this should resolve the odd behavior described in my last comment. Hopefully it has resolved this issue as well.

**Comment by aloucks** [comment]
I can still reproduce it.

When it happens, I see the request as either "pending" or as "failed" in the network tab. 

If I click the request and go to the "Timing" tab, it shows the following:

![image](https://user-images.githubusercontent.com/221559/83084329-9c694e00-a056-11ea-86ae-f55309272980.png)

This is the link in the "Explanation":

https://developers.google.com/web/tools/chrome-devtools/network/reference#timing-explanation

> **Timing breakdown phases explained**
> Here's more information about each of the phases you may see in the Timing tab:
> * **Queueing**. The browser queues requests when:
>   * There are higher priority requests.
>   * There are already six TCP connections open for this origin, which is the limit. Applies to HTTP/1.0 : > and HTTP/1.1 only.
>   * The browser is briefly allocating space in the disk cache
> * **Stalled**. The request could be stalled for any of the reasons described in Queueing.

Although it seems to show "pending" more often than "failed", when it does show failed, there's a little more info in the response headers:

```
Request URL: https://static.crates.io/readmes/tokio/tokio-0.2.21.html
Referrer Policy: no-referrer-when-downgrade
cache-control: public,max-age=604800
content-encoding: gzip
content-type: text/html
date: Thu, 28 May 2020 00:14:34 GMT
last-modified: Wed, 13 May 2020 19:02:31 GMT
server: AmazonS3
status: 200
vary: Accept-Encoding
via: 1.1 22e9d361a9c4153886c1c8aa0eb4ffa8.cloudfront.net (CloudFront)
x-amz-cf-id: u6mzWD9Jhl1ylcCLig3HrkA9ifSNJLcFTYm4kImhb-mpGJGJxsdxPw==
x-amz-cf-pop: IAD89-C3
x-amz-version-id: qqYxHeLvwS5rzF075.PP0jcCSEux5ozF
x-cache: Miss from cloudfront

Provisional headers are shown
DNT: 1
Referer: https://crates.io/crates/tokio
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
```

![image](https://user-images.githubusercontent.com/221559/83084783-fd455600-a057-11ea-930c-e588806cca59.png)


When I refresh until it works, I noticed that the `x-cache` header now indicates a cache hit. No idea if it's related, but it seems odd:

![image](https://user-images.githubusercontent.com/221559/83084947-7775da80-a058-11ea-911c-059408162096.png)

**Comment by jtgeibel** [comment]
Thanks for the additional info! I'm not really sure what is going on here. I had previously assumed the issue could be in the `https://crates.io/api/v1/crates/tokio/0.2.21/readme` step, which is a redirect to the actual HTML file stored on S3. However, it appears that the stalled request is to `https://static.crates.io/readmes/tokio/tokio-0.2.21.html` so this appears to be caused by S3 or CloudFront somehow.

**Comment by aloucks** [comment]
I **only** see it happen in chrome though, which is what's so strange.

**Comment by morigs** [comment]
Maybe this issue related to some extension that installed only in Chrome? @aloucks Do the issue persists in incognito mode?

**Comment by eminence** [comment]
I have this problem, too.  You have a good thought @morigs.  I use the uMatrix plugin to block ads and tracking stuff.  However, even when uMatrix is fully disabled for crates.io, I still see this problem.  However, I don't see this problem in an incognito window or a guest window.  (So more investigation needed here)

**Comment by aloucks** [comment]
> Do the issue persists in incognito mode?

This was a great suggestion! I could not reproduce the issue in Incognito mode!

It seems that `Requestly` was causing the issue. I haven't been able to reproduce it after disabling that addon. I'll leave the issue open in case others run into it, but feel free to close.

**Comment by mahkoh** [comment]
Fixed in nightly: https://bugs.chromium.org/p/chromium/issues/detail?id=938560#c27

**Comment by jtgeibel** [comment]
It sounds like this should be fixed in Chrome 85 (84 just went stable). I don't think there is anything else we can do here, so I'm closing this. Thanks for the help tracking this down everyone!
