### ISSUE TITLE
Redirecting to the latest crate should only use non-yanked versions

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/crates.io#510]
Right now, if I visit `https://crates.io/crates/quickcheck`, I am redirected to the "This crate has been yanked" page (for version 0.4.2). However, we could just instead redirect to 0.4.1, the previous non-yanked version.

**Comment by Eh2406** [comment]
related to #76

**Comment by pnkfelix** [comment]
also related to (but distinct from) #145

**Comment by carols10cents** [comment]
This has been fixed by the changes in #592 !

**Comment by carols10cents** [comment]
Ok, this is not fixed completely. If I navigate to https://crates.io/crates/quickcheck directly, I correctly end up on the page for quickcheck 0.4.1.

HOWEVER if I *search* for quickcheck and click the search result link, I still end up with a page that says "this crate has been yanked" :( Something's not hooked up the way ember needs it to be :(

**Comment by hoodie** [comment]
@carols10cents I'm still seeing this with `actix` right now
1. last "stable" version is `0.7.10` (yanked)
2. they just released `0.8.0-alpha.1`
3. suddenly the start page show "This crate has been yanked, but it is still available for download for other crates that may be depending on it."

**Comment by sgrif** [comment]
@hoodie That's the expected behavior. crates.io/crates/actix shows the latest non-prerelease version, which has been yanked.

**Comment by sgrif** [comment]
Scratch that, we should be redirecting to 0.7.9

**Comment by sgrif** [comment]
This should be fixed by #1684  which I am deploying now

**Comment by sgrif** [comment]
This appears to be fixed
