### ISSUE TITLE
crates.io shows old documentation link when documentation field removed from Cargo.toml

### ISSUE THREAD

**Issue by onur** [rust-lang/crates.io#945]
crates.io shows old documentation link when documentation field removed in the latest version of a crate.

[take_mut](https://crates.io/crates/take_mut) crate has `https://crates.fyi/crates/take_mut/0.1.3/` documentation link [in the version 0.1.3](https://docs.rs/crate/take_mut/0.1.3/source/Cargo.toml). Documentation link is removed in [the latest version](https://docs.rs/crate/take_mut/0.2.0/source/Cargo.toml.orig). But crates.io [shows](https://crates.io/crates/take_mut) old documentation link, used in 0.1.3.

**Comment by sgrif** [comment]
I need to double check, but the fix for this should be as simple as putting `#[treat_none_as_null = "true"]` [here](https://github.com/rust-lang/crates.io/blob/master/src/krate.rs#L57)

**Comment by sunjay** [comment]
I've started to work on this in https://github.com/rust-lang/crates.io/pull/948.

Any mentorship anyone can provide is welcome. I'll debug it more soon. :smile:

**Comment by sunjay** [comment]
I've fixed the issue in my PR and once it is merged any affected crates will need to publish before the webpage is updated. There are other larger issues which I've talked about in my PR which should be addressed at some point but I think are too big of a change for this issue.

**Comment by Sgeo** [comment]
I was under the impression that removing the documentation link will cause crates.io to use docs.rs as a default. Will that still occur with this fix?

**Comment by sunjay** [comment]
@Sgeo That behaviour seems to occur on the frontend and should continue to work as expected. Someone more familiar with the codebase should probably say more about that though. I'm just commenting based on what I saw when I looked just now.

**Comment by carols10cents** [comment]
>> I was under the impression that removing the documentation link will cause crates.io to use docs.rs as a default. Will that still occur with this fix?
>
> @Sgeo That behaviour seems to occur on the frontend and should continue to work as expected. Someone more familiar with the codebase should probably say more about that though. I'm just commenting based on what I saw when I looked just now.

Yes, @sunjay is correct: once this fix is deployed and new versions of the crates are published, the frontend will see that there is no documentation URL and will check docs.rs.

**Comment by Sgeo** [comment]
When will the fix be deployed? I assume it hasn't been deployed yet, because I republished take_mut and the issue is still present.

**Comment by carols10cents** [comment]
@Sgeo Just deployed, sorry about the delay!

**Comment by onur** [comment]
@carols10cents it still shows old documentation link.

cc @sunjay

**Comment by carols10cents** [comment]
@onur you will need to publish a new version since the deploy 20 hours ago.

**Comment by Sgeo** [comment]
@carols10cents Thank you! Republished and it's working.
